# Site settings
author: Michael Fuget
title: Michael Fuget Blog
header-img: img/home-bg.png
email: michaelfuget@gmail.com
copyright_name: Michael Fuget
description: > # this means to ignore newlines until "baseurl:"
  Engineering work and philosopy
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mkfuget

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
